---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: netscaler-operator-controller-manager
  namespace: default
  labels:
    control-plane: controller-manager
    app.kubernetes.io/name: deployment
    app.kubernetes.io/instance: controller-manager
    app.kubernetes.io/component: manager
    app.kubernetes.io/created-by: netscaler-operator
    app.kubernetes.io/part-of: netscaler-operator
    app.kubernetes.io/managed-by: kustomize
spec:
  selector:
    matchLabels:
      control-plane: controller-manager
  replicas: 1
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      labels:
        app.kubernetes.io/component: manager
        app.kubernetes.io/created-by: netscaler-operator
        app.kubernetes.io/instance: controller-manager
        app.kubernetes.io/managed-by: kustomize
        app.kubernetes.io/name: deployment
        app.kubernetes.io/part-of: netscaler-operator
        control-plane: controller-manager
    spec:
      securityContext:
        runAsNonRoot: true
      serviceAccountName: netscaler-operator-controller-manager
      terminationGracePeriodSeconds: 10
      containers:
        - args:
          - --secure-listen-address=0.0.0.0:8443
          - --upstream=http://127.0.0.1:8080/
          - --logtostderr=true
          - --v=0
          image: registry.redhat.io/openshift4/ose-kube-rbac-proxy@sha256:23405618050a4ceea8ea0c748cc7d9d16dbb80f10e4c39f7e82014a3ac80cec9
          name: kube-rbac-proxy
          ports:
          - containerPort: 8443
            name: https
            protocol: TCP
          resources:
            limits:
              cpu: 500m
              memory: 128Mi
            requests:
              cpu: 5m
              memory: 64Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
        - args:
          - --health-probe-bind-address=:8081
          - --metrics-bind-address=127.0.0.1:8080
          - --leader-elect
          - --leader-election-id=netscaler-operator
          command:
          - /manager
          image: registry.connect.redhat.com/citrix/netscaler-operator@sha256:3f71f9a46d7b29e3da98a301965f635c03a022b5535b586d7d5c699341f68193
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
          name: manager
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            limits:
              cpu: 500m
              memory: 500Mi
            requests:
              cpu: 200m
              memory: 200Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
