apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    ingress.citrix.com/insecure-termination: redirect
    kubernetes.io/ingress.class: citrix-ingress
  name: citrix-secure
spec:
  rules:
  - http:
      paths:
      - backend:
          service:
            name: test
            port:
              number: 80
        path: /testpath
        pathType: ImplementationSpecific
  tls:
  - {}
