apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
 name: guestbook
 annotations:
   kubernetes.io/ingress.class: “citrix”
   ingress.citrix.com/frontend-ip: 192.0.2.179
   ingress.citrix.com/canary-by-header: “header-name”
   ingress.citrix.com/canary-by-header-value: '[“value1”,“value2",“value3”,“value4"]'
spec:
 rules:
 - host: guestbook.com
   http:
     paths:
     - path: /
       pathType: Prefix
       backend:
         service:
           name: frontend
           port:
             number: 80