apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: canary-by-header
  annotations:
    kubernetes.io/ingress.class: "citrix"
    ingress.citrix.com/canary-by-header: "some-header-info"
spec:
  rules:
  - host:  webapp.com
    http:
      paths:
      - path: /
        backend:
          serviceName: guestbook-canary
          servicePort: 80