apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-host1
spec:
  rules:
  - host: example-host.example.com
    http:
      paths:
      - backend:
          service:
            name: apache
            port:
              number: 80
        pathType: Prefix
  - host: example-host2.example.com
    http:
      paths:
      - backend:
          service:
            name: apache
            port:
              number: 80
        pathType: Prefix
