apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: listeners.citrix.com
status:
spec:
  group: citrix.com
  version: v1alpha1
  names:
    kind: Listener 
    plural: listeners 
    singular: listener
  scope: Namespaced
  subresources:
    status: {}
  additionalPrinterColumns:
    - name: Status
      type: string
      description: "Current Status of the CRD"
      JSONPath: .status.state
    - name: Message
      type: string
      description: "Status Message"
      JSONPath: .status.status_message
  validation:
    openAPIV3Schema:
      required: [spec]
      properties:
        spec:
          type: object
          required: [protocol]
          properties:
            protocol:
              type: string
              enum: ["https", "http"]
              description: "Protocol for this listener"
            vip:
              type: string
              description: "Endpoint IP address, Optional for CPX, required for Tier-1 deployments"
            port:
              type: integer
              minimum: 1
              maximum: 65535
            certificates:
              type: array
              description: "certificates attached to the endpoints - Not applicable for HTTP"
              minItems: 1
              items:
                type: object 
                properties:
                  preconfigured:
                    type: string
                    description: "Preconfigured Certificate name on ADC "
                  secret:
                    type: object 
                    description: "Kuberentes secret object"
                    required: [name]
                    properties:
                      name:
                        type: string
                        description: "name of the Kubernetes Secret object where Cert is located"
                        pattern: '^[a-z0-9]([-a-z0-9]*[a-z0-9])?$'
                      namespace:
                        type: string
                        description: "Namespace of the kubernetes secret object; Default is same namespace where the Listener object is located"
                        pattern: '^[a-z0-9]([-a-z0-9]*[a-z0-9])?$'
                  default:
                    type: boolean
                    description: "Only one of the certificate can be marked as default which will be presented if none of the cert matches with the hostname"
            routes:
              type: array
              description: "List of route objects attached to the listener"
              minItems: 1
              items:
                type: object
                properties:
                  name:
                    type: string
                    description: "Name of the HTTPRoute object"
                    pattern: '^[a-z0-9]([-a-z0-9]*[a-z0-9])?$'
                  namespace:
                    type: string
                    description: "Namespace of the HTTPRoute object"
                    pattern: '^[a-z0-9]([-a-z0-9]*[a-z0-9])?$'
                  labelSelector:
                    description: "Labels key value pair, if the route carries the same labels, it is automatically attached"
                    type: object
                    additionalProperties:
                      type: string
                oneOf:
                - required: [name, namespace] 
                - required: [labelSelector]
            defaultAction:
              type: object
              description: "Default action for the listener: One of Backend or Redirect"
              properties:
                backend:
                  type: object
                  oneOf:
                  - required: [kube]
                  properties:
                    kube:
                      type: object
                      required: [service, port]
                      properties:
                        service:
                          description: "Name of the backend service"
                          type: string
                          pattern: '^[a-z0-9]([-a-z0-9]*[a-z0-9])?$'
                        port:
                          description: "Service port"
                          type: integer
                          minimum: 1
                          maximum: 65535
                        namespace:
                          description: "Service namespace"
                          type: string
                          pattern: '^[a-z0-9]([-a-z0-9]*[a-z0-9])?$'
                        backendConfig:
                          description: "General backend service options"
                          properties:
                            secure_backend:
                              description: "Use Secure communications to the backends"
                              type: boolean
                            lbConfig:
                              description: "Citrix ADC LB vserver configurations for the backend. Refer: https://developer-docs.citrix.com/projects/netscaler-nitro-api/en/12.0/configuration/load-balancing/lbvserver/lbvserver/ for all configurations"
                              type: object
                              additionalProperties:
                                type: string
                            servicegroupConfig:
                              description: "Citrix ADC service group configurations for the backend; Refer: https://developer-docs.citrix.com/projects/netscaler-nitro-api/en/12.0/configuration/basic/servicegroup/servicegroup/ for all configurations"
                              type: object
                              additionalProperties:
                                type: string
                redirect:
                  type: object
                  oneOf:
                  - required: [targetExpression]
                  - required: [hostRedirect]
                  - required: [httpsRedirect]
                  properties:
                    httpsRedirect:
                      description: "Change the scheme from http to https keeping URL intact"
                      type: boolean
                    hostRedirect:
                      description: "Host name specified is used for redirection with URL intact"
                      type: string
                    targetExpression:
                      description: "A target can be specified using Citrix ADC policy expression"
                      type: string
                    responseCode:
                      description: "Default response code is 302, which can be customised using this attribute"
                      type: integer
                      minimum: 100
                      maximum: 599
              oneOf:
              - required: ["backend"]
              - required: ["redirect"]
