apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: web-ingress
  annotations:
    ingress.citrix.com/insecure-port: "6080"
    kubernetes.io/ingress.class: "builtin-hostport"
spec:
  rules:
  - host: frontend.org
    http:
      paths:
      - path: /web-frontend/frontend.php
        backend:
          serviceName: frontend
          servicePort: 80
