VPX_IP="VPX_IP"
CPX_IMAGE="quay.io/citrix/citrix-k8s-cpx-ingress:13.0-47.103"
CIC_IMAGE="quay.io/citrix/citrix-k8s-ingress-controller:1.7.46"
EXPORTER="quay.io/citrix/citrix-adc-metrics-exporter:1.4.3"
VPX_PASSWORD="VPX_PASSWORD"
VPX_VIP="VIRTUAL_IP_VPX"
