kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: citrix
rules:
  - apiGroups: [""]
    resources: ["services", "endpoints", "ingresses", "pods", "secrets", "nodes", "routes", "routes/status", "tokenreviews", "subjectaccessreviews"]
    verbs: ["*"]
  - apiGroups: ["extensions"]
    resources: ["ingresses", "ingresses/status"]
    verbs: ["*"]
  - apiGroups: ["citrix.com"]
    resources: ["rewritepolicies"]
    verbs: ["*"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["*"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: citrix
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: citrix
subjects:
- kind: ServiceAccount
  name: citrix
  namespace: default
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: citrix
  namespace: default
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cpx-cic
spec:
  replicas: 1
  template:
    metadata:
      name: cpx-cic
      labels:
        app: cpx-cic
      annotations:
    spec:
      serviceAccountName: citrix
      containers:
        - name: cpx
          # Change the image with quay image
          image: "in-docker-reg.eng.citrite.net/cpx-dev/cpx:13.0-36.14"
          securityContext: 
             privileged: true
          env:
          - name: "EULA"
            value: "yes"
          - name: "KUBERNETES_TASK_ID"
            value: ""
          ports:
          - containerPort: 80
            hostPort: 80
          - containerPort: 443
            hostPort: 443
          imagePullPolicy: Always
        # Add cic as a sidecar
        - name: cic
          # Change the image with quay image
          image: "in-docker-reg.eng.citrite.net/cic-dev/cic:279"
          imagePullPolicy: Always
          env:
          - name: "EULA"
            value: "yes"
          - name: "NS_IP"
            value: "127.0.0.1"
          - name: "NS_PROTOCOL"
            value: "HTTP"
          - name: "NS_PORT"
            value: "80"
          - name: "NS_DEPLOYMENT_MODE"
            value: "SIDECAR"
          - name: "NS_ENABLE_MONITORING"
            value: "YES"
          - name: POD_NAME
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.name
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
          args:
            - --default-ssl-certificate
              $(POD_NAMESPACE)/default-cert
          imagePullPolicy: Always
