apiVersion: v1
kind: Route
metadata:
  name: secured-edge-route
spec:
  host: secured-edge-route.openshift.citrix-cic.com
  path: "/"
  to:
    kind: Service
    name: svc-apache-multi-http
  tls:
    termination: edge

    key: |-                      
      -----BEGIN RSA PRIVATE KEY-----
      ***REMOVED***
      
      
      
      
      
      
      
      
      
      
      
      ***REMOVED***
      
      
      
      
      
      
      
      
      
      
      
      
      -----END RSA PRIVATE KEY-----

    certificate: |-              
      -----BEGIN CERTIFICATE-----
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      GbqIML4OOBN+8pwByFp7T+3xAQ==
      -----END CERTIFICATE-----
