apiVersion: apps/v1
kind: Deployment
metadata:
  name: tea-beverage 
  labels:
      name: tea-beverage
spec:
  selector:
    matchLabels:
      app: tea-beverage
  replicas: 2 
  template:
    metadata:
      labels:
        app: tea-beverage
    spec:
      containers:
      - name: tea-beverage
        image: quay.io/sample-apps/hotdrinks:v1
        ports:
        - name: tea-80
          containerPort: 80
        - name: tea-443
          containerPort: 443
#        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: tea-beverage
spec:
  clusterIP: None
  ports:
  - name: tea-80
    port: 80
    targetPort: 80
  - name: tea-443
    port: 443
    targetPort: 443
  selector:
    app: tea-beverage

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: coffee-beverage 
  labels:
      name: coffee-beverage
spec:
  selector:
    matchLabels:
      app: coffee-beverage
  replicas: 2 
  template:
    metadata:
      labels:
        app: coffee-beverage
    spec:
      containers:
      - name: coffee-beverage
        image: quay.io/sample-apps/hotdrinks:v1
        ports:
        - name: coffee-80
          containerPort: 80
        - name: coffee-443
          containerPort: 443 
#        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: coffee-beverage
spec:
  clusterIP: None
  ports:
  - name: coffee-80
    port: 80
    targetPort: 80
  - name: coffee-443
    port: 443
    targetPort: 443
  selector:
    app: coffee-beverage

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-hotdrinks
spec:
  selector:
    matchLabels:
      app: frontend-hotdrinks
  replicas: 2 
  template:
    metadata:
      labels:
        app: frontend-hotdrinks
    spec:
      containers:
      - name: frontend-hotdrinks
        image: quay.io/sample-apps/hotdrinks:v1
        ports:
        - name: hotdrinks-80
          containerPort: 80
        - name: hotdrinks-443
          containerPort: 443
#        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-hotdrinks
spec:
  clusterIP: None
  ports:
  - name: hotdrinks-80
    port: 80
    targetPort: 80
  - name: hotdrinks-443
    port: 443
    targetPort: 443
  selector:
    app: frontend-hotdrinks

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    ingress.citrix.com/secure_backend: '{"coffee-beverage": "True"}'
    kubernetes.io/ingress.class: hotdrink
  name: hotdrinks-ingress
spec:
  rules:
  - host: hotdrink.beverages.com
    http:
      paths:
      - backend:
          service:
            name: frontend-hotdrinks
            port:
              number: 80
        path: /
        pathType: Prefix
  - host: tea
    http:
      paths:
      - backend:
          service:
            name: tea-beverage
            port:
              number: 80
        path: /
        pathType: Prefix
  - host: coffee
    http:
      paths:
      - backend:
          service:
            name: coffee-beverage
            port:
              number: 443
        path: /
        pathType: Prefix
  tls:
  - secretName: hotdrink-secret

---

apiVersion: v1
kind: Service
metadata:
  name: tea
spec:
  ports:
  - name: hotdrinks-80
    port: 80
    targetPort: 80
  - name: hotdrinks-443
    port: 443
    targetPort: 443
  selector:
    app: cpx-ingress

---


apiVersion: v1
kind: Service
metadata:
  name: coffee
spec:
  ports:
  - name: hotdrinks-80
    port: 80
    targetPort: 80
  - name: hotdrinks-443
    port: 443
    targetPort: 443
  selector:
    app: cpx-ingress
