{{- $default := .Values.setAsDefaultIngressClass -}}
{{- if semverCompare ">=1.19.0-0" .Capabilities.KubeVersion.GitVersion }}
{{- if .Values.ingressClass }}
{{- range .Values.ingressClass }}
apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: {{ . | quote }}
{{- if $default }}
  annotations:
    ingressclass.kubernetes.io/is-default-class: "true"
{{- end }}
spec:
  controller: citrix.com/ingress-controller
---
{{- end }}
{{- end }}
{{- end }}
