apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: wildcarddnsentries.citrix.com
spec:
  group: citrix.com
  names:
    kind: wildcarddnsentry
    plural: wildcarddnsentries
    singular: wildcarddnsentry
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      subresources:
        status: {}
      additionalPrinterColumns:
        - name: Status
          type: string
          description: Current Status of the CRD
          jsonPath: .status.state
        - name: Message
          type: string
          description: Status Message
          jsonPath: .status.status_message
      schema:
        openAPIV3Schema:
          type: object
          properties:
            status:
              type: object
              properties:
                state:
                  type: string
                status_message:
                  type: string
            spec:
              type: object
              properties:
                zone:
                  type: object
                  description: DNS configuration for a zone
                  properties:
                    domain:
                      type: string
                      description: Domain name
                    dnsaddrec:
                      type: object
                      description: DNS Address record
                      properties:
                        domain-ip:
                          type: string
                          description: IPv4 addresses to assign to the domain name
                        ttl:
                          type: integer
                          description: >-
                            TTL is the time for which the record must be cached
                            by DNS proxies
                    dnsaaaarec:
                      type: object
                      description: DNS AAAA record
                      properties:
                        domain-ip:
                          type: string
                          description: IPv6 addresses to assign to the domain name
                        ttl:
                          type: integer
                          description: >-
                            TTL is the time for which the record must be cached
                            by DNS proxies
                    soarec:
                      type: object
                      description: SOA record
                      properties:
                        origin-server:
                          type: string
                          description: Origin server domain
                        contact:
                          type: string
                          description: Admin contact
                        serial:
                          type: integer
                          description: >-
                            The secondary server uses this parameter to
                            determine whether it requires a zone transfer from
                            the primary server.
                        refresh:
                          type: integer
                          description: >-
                            Time, in seconds, for which a secondary server must
                            wait between successive checks on the value of the
                            serial number.
                        retry:
                          type: integer
                          description: >-
                            Time, in seconds, between retries if a secondary server's 
                            attempt to contact the primary server for a zone refresh fails.
                        expire:
                          type: integer
                          description: >-
                            Time, in seconds, after which the zone data on a secondary 
                            nameserver can no longer be considered authoritative because
                            all refresh and retry attempts made during the period have failed."
                    nsrec:
                      type: object
                      description: Name server record
                      properties:
                        nameserver:
                          type: string
                          description: Host name of the name server to add to the domain.
                        ttl:
                          type: integer
                          description: >-
                            Time to Live (TTL), in seconds, for the record. TTL
                            is the time for which the record must be cached by
                            DNS proxies. The specified TTL is applied to all the
                            resource records that are of the same record type
                            and belong to the specified domain name