apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: citrix-tier-2
  name: citrix-tier-2-ingress
spec:
  rules:
  - host: anthos-citrix-ingress.com
    http:
      paths:
      - backend:
          service:
            name: apache
            port:
              number: 80
        path: /
        pathType: Prefix
  tls:
  - secretName: anthos-citrix
