apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition 
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: continuousdeployments.citrix.com
spec:
  group: citrix.com
  names:
    kind: continuousdeployment
    plural: continuousdeployments
    singular: continuousdeployment
  scope: Namespaced
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            x-kubernetes-preserve-unknown-fields: true
            properties:
              cronSpec:
                type: integer
