apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    ingress.citrix.com/deployment: dsr
    ingress.citrix.com/frontend-ip: x.x.x.x
    kubernetes.io/ingress.class: dsr
  name: cpx-ingress
spec:
  defaultBackend:
    service:
      name: cpx-service
      port:
        number: 80
