apiVersion: v1
appVersion: "1.4.392"
description: A Helm chart for Citrix ADC CPX with Citrix ingress Controller running as sidecar.
name: citrix-k8s-cpx-ingress-controller
version: 1.4.392
icon: https://raw.githubusercontent.com/citrix/citrix-k8s-ingress-controller/gh-pages/icon.png
home: https://www.citrix.com
sources:
- https://github.com/citrix/citrix-k8s-ingress-controller
maintainers:
- name: Priyanka Sharma
  email: priyanka.sharma@citrix.com
- name: Subash Dangal
  email: subash.dangol@citrix.com
