apiVersion: citrix.com/v1alpha1
kind: Listener
metadata:
  annotations:
  name: listener-redirect
  namespace: default
spec:
  # VIP is mandatory for tier-1 ADC and not required for tier-2 CPX
  vip: 10.0.0.1
  port: 80
  protocol: http
  # default action as redirect to https
  defaultAction:
    redirect:
      httpsRedirect: true
