          apiVersion: networking.k8s.io/v1
          kind: Ingress
          metadata:
            name: dbs-ingress
            annotations:
              kubernetes.io/ingress.class: "cpx-ingress"
              ingress.citrix.com/external-service: '{"external-svc": {"domain": "www.externalsvc.com"}}'
          spec:
            rules:
            - host:  "www.externalsvc.com"
              http:
                paths:
                - backend:
                    service:
                      name: external-svc
                      port:
                        number: 30036
                  path: /
                  pathType: Prefix
