apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: canarydemo
  name: fronthotdrinksapp
  namespace: default
spec:
  rules:
  - host: canarydemo.com
    http:
      paths:
      - backend:
          service:
            name: fronthotdrinksapp
            port:
              number: 8080
        path: /
        pathType: ImplementationSpecific
