apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    ingress.citrix.com/secure-backend: '{"spin-deck":"True", "spin-gate":"True"}'
    kubernetes.io/ingress.class: canarydemo
  labels:
    app: spin
    cluster: spin-ingress
  name: spin-ingress
  namespace: spinnaker
spec:
  rules:
  - host: spinnaker.example.com
    http:
      paths:
      - backend:
          service:
            name: spin-deck
            port:
              number: 9000
        pathType: Prefix
        path: /
  - host: spinnaker-api.example.com
    http:
      paths:
      - backend:
          service:
            name: spin-gate
            port:
              number: 8084
        pathType: Prefix
        path: /
  tls:
  - hosts:
    - spinnaker.example.com
    secretName: newcert
  - hosts:
    - spinnaker-api.example.com
    secretName: newcert
