---
apiVersion: v1
kind: ServiceAccount
metadata:
   name: citrix-ipam-controller
   namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
   name: citrix-ipam-controller
rules:
 - apiGroups:
   - citrix.com
   resources:
   - vips
   verbs:
   - '*'
 - apiGroups:
   - apiextensions.k8s.io
   resources:
   - customresourcedefinitions
   verbs:
   - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
   name: citrix-ipam-controller
subjects:
 - kind: ServiceAccount
   name: citrix-ipam-controller
   namespace: kube-system
roleRef:
   kind: ClusterRole
   apiGroup: rbac.authorization.k8s.io
   name: citrix-ipam-controller
---
apiVersion: apps/v1
kind: Deployment
metadata:
   labels:
     app: citrix-ipam-controller
   name: citrix-ipam-controller
   namespace: kube-system
spec:
   replicas: 1
   selector:
     matchLabels:
       app: citrix-ipam-controller
   template:
     metadata:
       labels:
         app: citrix-ipam-controller
     spec:
       serviceAccountName: citrix-ipam-controller
       containers:
       - image: quay.io/citrix/citrix-ipam-controller:latest
         imagePullPolicy: IfNotPresent
         name: citrix-ipam-controller
         env:
         # This IPAM controller takes environment variable VIP_RANGE. IPs in this range are used to assign values for IP range
         - name: VIP_RANGE
           value: '[["172.18.222.185"]]'
