apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: globaltrafficpolicies.citrix.com
spec:
  # group name to use for REST API: /apis/<group>/<version>
  group: citrix.com
  # list of versions supported by this CustomResourceDefinition
  version: v1beta1
  #    - name: v1
      # Each version can be enabled/disabled by Served flag.
      #      served: true
      # One and only one version must be marked as the storage version.
      #storage: true
  # either Namespaced or Cluster
  scope: Namespaced
  subresources:
    status: {}
  additionalPrinterColumns:
    - name: Status
      type: string
      description: "Current Status of the CRD"
      JSONPath: .status.state
    - name: Message
      type: string
      description: "Status Message"
      JSONPath: .status.status_message
  names:
    # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    plural: globaltrafficpolicies
    # singular name to be used as an alias on the CLI and for display
    singular: globaltrafficpolicy
    # kind is normally the CamelCased singular type. Your resource manifests use this.
    kind: globaltrafficpolicy
    # shortNames allow shorter string to match your resource on the CLI
    shortNames:
    - gtp
 
  validation:
  # openAPIV3Schema is the schema for validating custom objects.
    openAPIV3Schema:
      required: ["apiVersion","kind","metadata","spec"]
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          required: ["name","namespace"]
          properties:
            name:
              type: string
            namespace:
              type: string
          type: object
        spec:
          required: ["serviceType","hosts","status"]
          properties:
            ipType:
              type: string
              enum:
              - ipv4
              description: "Type of address A or AAAA. Currently only A is supported"
            serviceType:
              type: string
              enum:
              - HTTP
              - SSL
              - TCP
              - UDP
              - ANY
              description: "Protocol supported in multi-cluster deployment"
            hosts:
              items:
                required: ["host","policy"]
                properties:
                  host:
                    type: string
                    description: "Domain for which multi-cluster support will be applied"
                  policy:
                    required: ["targets","trafficPolicy"]
                    properties:
                      trafficPolicy:
                        type: string
                        enum:
                        - LOCAL-FIRST
                        - CANARY
                        - FAILOVER
                        - RTT
                        - ROUNDROBIN
                        - STATICPROXIMITY
                        description: "The traffic distribution policy supported in multi-cluster deployment"
                      secLbMethod:
                        type: string
                        description: "The traffic distribution policy supported among clusters under a group in local-first, canary or failover"
                      targets:
                        items:
                          required: ["destination"]
                          properties:
                            destination:
                              type: string
                              description: "Ingress or LoadBalancer service endpoint in each cluster. Should match with name of GSE"
                            weight:
                              type: integer
                              minimum: 1
                              maximum: 100
                              description: "Proportion of traffic to be maintained across clusters. For canary proportion is percentage"
                            rule:
                              type: string
                            CIDR:
                              type: string
                              description: "CIDR to be used in local-first to determine the scope of locality"
                            primary:
                              type: boolean
                              description: "Is this destination a primary cluster or a backup cluster in failover deployment. Possible values: True or False"
                          type: object
                        type: array
                    type: object
                  monitor:
                    items:
                      properties:
                        monType:
                          type: string
                          enum:
                          - PING
                          - TCP
                          - HTTP
                          - HTTPS
                          description: "Type of probe to determine the health of multi-cluster endpoint"
                        uri:
                          type: string
                          description: "Path to be probed for the health of multi-cluster endpoint in case of http and https"
                        respCode:
                          type: integer
                          description: "Response code expected to mark the multi-cluster endpoint healthy in case of http and https"
                      type: object
                    type: array
                type: object
              type: array
            status:
              type: object
          type: object
