apiVersion: citrix.com/v1
kind: waf
metadata:
    name: wafhtmlxsssql
spec:
    servicenames:
        - frontend
    html_error_object: "http://10.106.102.242/crd/hipster.html"
    security_checks:
        html:
          cross_site_scripting: "on" 
          sql_injection: "on"
