apiVersion: citrix.com/v1
kind: waf
metadata:
    name: wafhdrbufferoverflow
spec:
    servicenames:
        - frontend
    application_type: HTML
    html_page_url: "http://10.217.14.99/crd/error_page.html"
    security_checks:
        common:
          buffer_overflow: "on"
          #multiple_headers: ["block", "log"]
          multiple_headers:
            action: ["block", "log"]
    settings:
        common:
          buffer_overflow:
            max_cookie_len: 409
            max_header_len: 4096
            max_url_len: 1024
    ip_reputation: "on"
