apiVersion: citrix.com/v1
kind: bot
metadata:
  name: botblocklist
spec:
  servicenames:
    - frontend
  redirect_url: "/error_page.html"
  signatures: "http://10.106.102.242/ganeshka/bot_sig.json"
  target:
    path:
      - index.html
      - payment.php
      - login.php
    method:
      - GET
      - POST
    header:
      - Host
  security_checks:
    block_list: "ON"
  bindings:
    block_list:
      - subnet:
          value:
            - 172.16.1.0/12
            - 172.16.2.0/12
            - 172.16.3.0/12
            - 172.16.4.0/12
          action: ["drop"]
      - ip:
          value: 10.102.30.40
            - expression:
                value:  http.req.url.contains("/robots.txt")
                action: ["reset","log"]

