apiVersion: citrix.com/v1
kind: bot
metadata:
  name: botiprepcategory
spec:
  servicenames:
    - frontend
  redirect_url: "/error_page.html"
  target:
    path:
      - index.html
      - payment.php
      - login.php
    method:
      - GET
      - POST
    header:
      - Host
  security_checks:
    reputation: "ON"
  bindings:
    reputation:
      categories: 
        - SPAM_SOURCES:
            action: ["log", "redirect"]
        - MOBILE_THREATS
        - SPAM_SOURCES

