apiVersion: citrix.com/v1
kind: bot
metadata:
    name: botkeyboardm
spec:
  servicenames:
    - frontend
  redirect_url: "/error_page.html"
  signatures: "http://10.106.102.242/ganeshka/bot_sig.json"
  target:
    path:
      - index.html
      - payment.php
      - login.php
    method:
      - GET
      - POST
    header:
      - Host
  bindings:
    - rule:
        name: kbmexpr
        expression: 'true'
    - rule:
        name: keyboar mouse bot expression
        expression: 'http.req.url.startswith("/testsite")'
