apiVersion: citrix.com/v1
kind: bot
metadata:
    name: botlogexpression
spec:
  servicenames:
    - frontend
  redirect_url: "/error_page.html"
  signatures: "http://10.106.102.242/ganeshka/bot_sig.json"
  target:
    path:
      - index.html
      - payment.php
      - login.php
    method:
      - GET
      - POST
    header:
      - Host
  bindings:
    logexp:
      - rule:
          name: logehkp
          expression: 'HTTP.REQ.URL'
          comment: xkhresfffff
      - rule:
          name: logexpression bot expr
          expression: 'true'
          comment: expred
