apiVersion: citrix.com/v1
kind: bot
metadata:
  name: bottps
spec:
  servicenames:
    - frontend
  redirect_url: "/error_page.html"
  target:
    path:
      - index.html
      - payment.php
      - login.php
    method:
      - GET
      - POST
    header:
      - Host
  security_checks:
    tps: "ON"
  bindings:
    tps:
      geolocation:
        threshold: 101
        percentage: 100
      host:
        threshold: 10
        percentage: 100
        action: ["log", "reset"]
