apiVersion: citrix.com/v1
kind: bot
metadata:
  name: trapinsertion
spec:
  servicenames:
    - frontend
  redirect_url: "/error_page.html"
  signatures: "http://10.106.102.242/ganeshka/bot_sig.json"
  target:
    path:
      - index.html
      - payment.php
      - login.php
    method:
      - GET
      - POST
    header:
      - Host
 
  security_checks:
       trap:
         action: ["LOG", "DROP"]
  bindings:
    trapinsertion:
      urls:
        - /index.html
        - /submit.php
        - /login.html
