apiVersion: v1
kind: Service
metadata:
  name: cpx-service-lb
  labels:
    app: cpx-service-lb
spec:
  type: LoadBalancer
  loadBalancerIP: <VIP-for-accessing-microservices>
  ports:
  - port: 80
    protocol: TCP
    name: http
  - port: 443
    protocol: TCP
    name: https
  selector:
    app: cpx-ingress
