apiVersion: v1
appVersion: "1.5.25"
description: A Helm chart for Citrix ADC CPX with inbuilt ingress Controller
name: citrix-k8s-cpx-ingress-controller
version: 1.5.25
home: https://www.citrix.com
sources:
- https://github.com/citrix/citrix-k8s-ingress-controller
maintainers:
- name: Citrix CIC Team
  email: NSCPXOrchestration@citrite.net
