# Default values for citrix-k8s-cpx-ingress-controller.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
cpx:
  image: quay.io/citrix/citrix-k8s-cpx-ingress:13.0-36.29
  pullPolicy: Always
cic:
  image: quay.io/citrix/citrix-k8s-ingress-controller:1.4.392
  pullPolicy: Always
  required: true
license:
  accept: no
ingressClass: ["Citrix"]
exporter: 
  required: false
  image: quay.io/citrix/citrix-adc-metrics-exporter:1.3
  pullPolicy: Always
  ports:
       containerPort: 8888
