# Default values for citrix-k8s-cpx-ingress-controller.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
cpximage:
  repository: quay.io/citrix/citrix-k8s-cpx-ingress
  tag: 12.1-51.16
  pullPolicy: Always
cicimage:
  repository: quay.io/citrix/citrix-k8s-ingress-controller
  tag: 1.1.1
  pullPolicy: Always
license:
  accept: no
ingressClass: ["Citrix"]
exporter: 
  require: 0
  image:
       repository: quay.io/citrix/netscaler-metrics-exporter
       tag: v1.0.0
       pullPolicy: Always
  ports:
       containerPort: 8888
