apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: canary-by-weight
  annotations:
    kubernetes.io/ingress.class: "citrix"
    ingress.citrix.com/canary-weight: "40"
    ingress.citrix.com/frontend-ip: 1.1.1.1

spec:
  rules:
  - host:  demo-canary.webapp.com
    http:
      paths:
      - path: /
        backend:
          serviceName: guestbook-canary
          servicePort: 80
