apiVersion: citrix.com/v1
kind: rewritepolicy
metadata:
 name: httpxforwardedforaddition
spec:
 rewrite-policies:
   - servicenames:
       - guestbook
     rewrite-policy:
       operation: insert_http_header
       target: X-Forwarded-For
       modify-expression: client.ip.src
       comment: 'HTTP Initial X-Forwarded-For header add'
       direction: REQUEST
       rewrite-criteria: 'HTTP.REQ.HEADER("X-Forwarded-For").EXISTS.NOT'
   - servicenames:
       - guestbook
     rewrite-policy:
       operation: replace
       target: HTTP.REQ.HEADER("X-Forwarded-For")
       modify-expression: 'HTTP.REQ.HEADER("X-Forwarded-For").APPEND(",").APPEND(CLIENT.IP.SRC)'
       comment: 'HTTP Append X-Forwarded-For IPs'
       direction: REQUEST
       rewrite-criteria: 'HTTP.REQ.HEADER("X-Forwarded-For").EXISTS'