apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: apigatewaypolicies.citrix.com
spec:
  group: citrix.com
  version: v1beta1
  names:
    kind: apigatewaypolicy
    plural: apigatewaypolicies
    singular: apigatewaypolicy
  scope: Namespaced
  subresources:
    status: {}
  additionalPrinterColumns:
    - name: Status
      type: string
      description: "Current Status of the CRD"
      JSONPath: .status.state
    - name: Message
      type: string
      description: "Status Message"
      JSONPath: .status.status_message

